In [3]:
from array import *
def array_list(array_num): 
    num_list = array_num.tolist() 
    print(num_list) 
array_num = array('i', [4,5,3,4,6,7])
array_list(array_num) 

[4, 5, 3, 4, 6, 7]


In [7]:
import numpy as np
m = np.arange(4).reshape(2,2)
print("matrix:")
print(m)
result =  np.trace(m)
print("Sum:")
print(result)

matrix:
[[0 1]
 [2 3]]
Sum:
3


In [10]:
import numpy as np
x=np.array([[1,2],[3,5]])
print("bigger than X:",x[x>3])

bigger than X: [5]


In [20]:
import numpy as np
A=np.array([2,3])
B=np.array([[6,8]])
C=A+B
print(C)
type(C)

[[ 8 11]]


numpy.ndarray

In [28]:
import numpy as np
X = np.array([9,7])
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean()
Y


Subtract the mean of each row of the said matrix:



array([ 1., -1.])